org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m
org.gradle.java.installations.auto-download=true

# Environment
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
neo_version=26.1.0.1-beta
loader_version_range=[1,)

# Mod metadata
mod_id=inputbooster
mod_name=InputBooster
mod_license=MIT
mod_version=3.0.3nf-mc261
mod_group_id=dev.inputbooster
