package dev.inputbooster;

public enum InputAction {
    ATTACK_PRESSED, ATTACK_RELEASED,
    USE_PRESSED, USE_RELEASED,
    SPRINT_PRESSED, SPRINT_RELEASED,
    SNEAK_PRESSED, SNEAK_RELEASED,
    JUMP_PRESSED,
    FORWARD_PRESSED, FORWARD_RELEASED,
    BACK_PRESSED, BACK_RELEASED,
    LEFT_PRESSED, RIGHT_PRESSED,
    DROP_PRESSED,
    SWAP_PRESSED,
    PICK_BLOCK_PRESSED
}
